In [1]:
!pip install numpy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.8 kB 217.9 kB/s eta 0:00:01
     ------------ ------------------------- 20.5/60.8 kB 217.9 kB/s eta 0:00:01
     ------------------------- ------------ 41.0/60.8 kB 217.9 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 262.6 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 180.1 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB 1.3 MB/s eta 0:00:10
   ---------------------------------------- 0.1/12.6 MB 1.3 MB/s eta 0:00:10
   ---------------------------------------- 0.2/12.6 MB 1.3 MB/s eta 0:00:10
    --------------------------------------- 0.2/12.6 MB 1.0 MB/s eta 0:00:


[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
#Defining a numpy array with numbers and a string elements
a=np.array([1,2,3,'R'])

In [4]:
#print a 
a

array(['1', '2', '3', 'R'], dtype='<U21')

In [6]:
a=np.array(10)
b=np.array([10,20,30])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [74]:
#printing the dimension names of above mentioned arrays
print("a dimension name is:",a.ndim)#ndim function prints the dimention type
print("b dimension name is :",b.ndim)
print("c dimension name is :",c.ndim)
print("d dimension name is :",d.ndim)

a dimension name is: 0
b dimension name is : 1
c dimension name is : 2
d dimension name is : 3


In [9]:
print(a)
print("Shape of a is:",a.shape)
print(b)
print("Shape of b is:",b.shape)
print(c)
print("Shape of c is:",c.shape)
print(d)
print("Shape of d is:",d.shape)

10
Shape of a is: ()
[10 20 30]
Shape of b is: (3,)
[[1 2 3]
 [4 5 6]]
Shape of c is: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape of d is: (2, 2, 3)


In [23]:
#print the datatype of the elements in variable c and d
print(c.dtype)
print(d.dtype)
#print(b.dtype)

int64
int64
int64


In [17]:
#print the type of the variable a,b,c,d
print(type(a))
print(type(b))
print(type(c))
print(type(d))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [24]:
#Length of the array 
len(d)

2

In [ ]:
Creating Numpy arrays
There are multiple ways to create the arrays in Numpy

In [36]:
#Using a range function creat a numpy array using from 1 to 11
abc=np.arange(1,10)
print(abc)
#Shape of this array is (10,) and it is 1D

[1 2 3 4 5 6 7 8 9]


In [62]:
#create numpy array using the eye 
np.eye(10,dtype=int)
#output is 2D whith shape(10,10)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [70]:
#create a numpy array with zero function with parameters (3,2) 3 rows and 2 columns
np.zeros((3,2),dtype='int')#Default datatype id float


array([[0, 0],
       [0, 0],
       [0, 0]])

In [72]:
#create a numpy array with complete 1's for a shape (5,4) with ones function
np.ones((5,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [77]:
#create a numpy array using the full function with a shape(5,5) and a element 3
a=5
b=5
np.full((a,b),3)#Either I can pass the elements or variable to this function

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [88]:
#create a numpy array usingthe diag function by passing a list [1,2,3,4,5,6]
list1=[1,2,3,4,5]#We can give list of any numbers like [3,5.64,1,73,68]
np.diag(list1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [95]:
#Reshape function
x=np.arange(1,9)#
print(x)
print(x.shape)
print(x.ndim)

[1 2 3 4 5 6 7 8]
(8,)
1


In [99]:
#Reshape above 1D array to 2D array using reshape function with shape(2,4)
n=x.reshape(2,4)
print(n)
print("shape",n.shape)
print("Dimension",n.ndim)

[[1 2 3 4]
 [5 6 7 8]]
shape (2, 4)
Dimension 2


In [101]:
#reshape the array n to 3D using the shape(2,2,2)
n1=n.reshape(2,2,2)
print(n1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [105]:
#using the ravel function--This function brings any dimension to 1D
rav=n.ravel()
print(rav.shape)
print(rav)
print(rav.ndim)

(8,)
[1 2 3 4 5 6 7 8]
1


In [106]:
#using the flatten function--This function brings any dimension to 1D
flt=n.flatten()
print(flt.shape)
print(flt)
print(flt.ndim)

(8,)
[1 2 3 4 5 6 7 8]
1


In [110]:
#Array Index to accesss the individual elements
a=np.arange(2,18,2)
print(a)
a

[ 2  4  6  8 10 12 14 16]


array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [117]:
#Acces the specifiic element from array
print(a[4])
a[4]#it gvies the value at index position 4 along with typ and OS

10


np.int64(10)

In [120]:
#Slicing on 1D array named a
a[0:9:2]
a[:9:2]

array([ 2,  6, 10, 14])

In [127]:
#performing the Indexing and slicing on 2D array
a=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a.shape)
print(a.ndim)
a

(3, 3)
2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
#print the 3rd element from the 3rs row
a[2,2]
print(a[2,2])

9


In [131]:
#print the element 8 from the 3rs row
print(a[2,1])

8


In [137]:
#print the shape of a array
a=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])
print(a.shape)
print(a.ndim)
a#Create the a 3D array form a list

(2, 2, 3)
3


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 8,  9, 10],
        [11, 12, 13]]])

In [140]:
# Acces the elements from the 3D array
#Print the elenent 12 from above 3D array(2,2,3)
# So 12 is in layer 2 and its index is 1,its in 2ns row qith index 1,its in 2nd colums and its index is 1
print(a[1][1][1])

12


In [143]:
#print the element in 1st layes 2rd row and 3nd column
print(a[0][1][2])

6


In [144]:
#Array slicing in 1D

arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
#Sliceing--extract elements from 4 to 8
arr[3:8]#here 3 and 8 are not elements they are index positions
arr[0:10:2]

array([1, 3, 5, 7, 9])

**slicing on 2D array**

In [148]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(a.shape)
print(a.ndim)
a

(3, 3)
2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
#In array a print index 2 for all rows
print(a[:,2])

[3 6 9]


In [173]:
#Printthe elements 2 5 8 as output
print(a[:,1])

[2 5 8]


In [175]:
#from all elements in a slice from index 1 till end
a[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

**Numpy copy vs view**

In [176]:
x1=np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
#assign x2 to x1
x2=x1
#print both x1 and x2
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [178]:
#change the 1st element in x2 as 10
x2[0]=10
print(x1)#We can see the changes reflected to x1 as well
print(x2)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [179]:
x3=x1.view()
print(x1)
print(x2)
print(x3)

[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]
[10  1  2  3  4  5  6  7  8  9]


In [180]:
x3[0]=100
print(x1)
print(x2)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [182]:
#create a copy x4 which is a copy of x1
x4=np.copy(x1)
print(x1)
print(x2)
print(x3)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [184]:
#change the last elemt of x4 as 99
x4[-1]=99
print(x1)
print(x2)
print(x3)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8  99]


**Conditions on arrays**

In [188]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a            

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [189]:
#check which elements in array a a re greter than 3
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [196]:
#List element which a re greater than 3
a[a>3]#This means from array a select those elements which a re greater than 3

array([4, 5, 6, 7, 8, 9])

In [197]:
#Checking the 2 conditions for 1 array
a[(a>3) & (a<8)]

array([4, 5, 6, 7])

In [202]:
#Checking the elements in x1 array are equal to array x5
x5=x1[::-1]
print(x1)
print(x5)
x5==x1#returns true 

[100   1   2   3   4   5   6   7   8   9]
[  9   8   7   6   5   4   3   2   1 100]


array([False, False, False, False, False, False, False, False, False,
       False])

**Transpose of matrix**
*It converts from rows to columns and columns to rows*

In [205]:
#print transpose of a
print(a.transpose())
a

[[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**hstack vs vstack**

In [211]:
print(x1.ndim)#This is 1D
print(x5.ndim)#This is 1D
print(va.ndim)#after stack it become 2D
va=np.vstack((x1,x5))#Vertical stack
va

1
1
2


array([[100,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [  9,   8,   7,   6,   5,   4,   3,   2,   1, 100]])

In [213]:
np.hstack((x1,x5))#Horizontal stack

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,   9,   8,   7,
         6,   5,   4,   3,   2,   1, 100])

In [214]:
#inserting the valus of X1 array into x5 arrat at a specified index position example at 4
print(x1)
print(x5)

[100   1   2   3   4   5   6   7   8   9]
[  9   8   7   6   5   4   3   2   1 100]


In [217]:
ins_arr=np.insert(x1,4,x2)

In [218]:
print(ins_arr)

[100   1   2   3 100   1   2   3   4   5   6   7   8   9   4   5   6   7
   8   9]


In [220]:
np.delete(x5,1)# this is X5 array [  9   8   7   6   5   4   3   2   1 100] ,We can see 8 missing in output for inxex 1 in x5

array([  9,   7,   6,   5,   4,   3,   2,   1, 100])

In [222]:
#sorting a array x5 .Default ascending
print(x5)
np.sort(x5)

[  9   8   7   6   5   4   3   2   1 100]


array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 100])

In [228]:
#sorting a array x5 in decending order
print(x5)
np.sort(x5)[::-1]

[  9   8   7   6   5   4   3   2   1 100]


array([100,   9,   8,   7,   6,   5,   4,   3,   2,   1])

In [233]:
#using the where function
arr1=np.where(x5>6)
arr1

(array([0, 1, 2, 9]),)

In [234]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
